// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"ArthaFreestyle/go-rest-api/app"
	"ArthaFreestyle/go-rest-api/controller"
	"ArthaFreestyle/go-rest-api/repository"
	"ArthaFreestyle/go-rest-api/service"
	"github.com/go-playground/validator"
)

// Injectors from injector.go:

func InitializedService() controller.CategoryController {
	categoryRepository := repository.NewCategoryRepository()
	db := app.NewDB()
	validate := validator.New()
	categoryService := service.NewCategoryService(categoryRepository, db, validate)
	categoryController := controller.NewCategoryController(categoryService)
	return categoryController
}
